### PR TITLE
Add Web Interface and easy motion notifications

### PR DESCRIPTION
**Pull request by williamkennyAK**
I have created push webhooks and integrated in mqtt notifications.

Also, developed a quick and dirty web interface which can do the following:
 - Easily configure motion notifications
 - Start an ftp server on device
 - Integrated in upload.html and upload.cgi
 - Reboot the camera
 This all runs on web server running on port 80.

I plan on continuing work on the web interface, but it is in a stable state ATM.

### CODE REVIEW

**Comment by williamkennyAK** [comment]
They are the same.  This is probably the result of me working on this after the kids went to bed until like 3am.

This is actually the absolute first time I've messed with any cgi stuff, but I've been messing around with Linux for 20+ years.  sh is sh.

**Comment by williamkennyAK** [comment]
Agreed, but what I intend to do is save a snap to send as a notification via telegram.  I'm starting an ftp server on there which is mounted to my nas which is accessible from home assistant.  This way, I can do a telegram notification with a snapshot, and offload videos and images to the nas daily.

**Comment by williamkennyAK** [comment]
Probably t he one thing I want to figure out the most is how to mount an nfs share on the camera that way I can just save snaps and video directly to my nas.

**Comment by guino** [comment]
The kernel/drivers in these devices are not capable of nfs mounts. 

The best option I see is having whatever receives the motion alert pull the jpeg image using snap.cgi and send the telegram message. It is file-less and most of the intensive work happens outside of the device.

**Comment by williamkennyAK** [comment]
It also makes me wonder what the possibility of putting a custom image on these devices.  Would it be possible to build a replacement firmware that is more open?  Something that allows us to run a more efficient rtsp/onvif server?  I'm gonna have to do some digging to see what's out there.

Have you looked into the OTA update process of these devices?  I wouldn't mind sacrificing one of these cameras to more of a teardown if there is a possibility of it working.

**Pull request closed without merging**
